In [1]:
import tensorflow as tf
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3])
print(array)

# Convert the NumPy array to a TensorFlow tensor
tensor = tf.convert_to_tensor(array)

# Print the tensor
print(tensor)


[1 2 3]
tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [2]:
import numpy as np
import torch

# Create a NumPy array
array = np.array([1, 2, 3])
print(array)

# Convert the NumPy array to a PyTorch tensor
tensor = torch.from_numpy(array)

# Print the tensor
print(tensor)


[1 2 3]
tensor([1, 2, 3])
